export const universityCardData = [
  {
    id: 1,
    logo: "https://upload.wikimedia.org/wikipedia/en/f/ff/Amity_University_logo.png",
    emiPlan: true,
    image:
      "https://www.learningroutes.in/_next/image?url=https%3A%2F%2Faskusedu.com%2Fblogdashboard%2Fwp-content%2Fuploads%2F2024%2F04%2FAmity-Mohali.webp&w=1920&q=75",
    rating: "A+",
    naac: "NAAC",
    creditPoints: "90+",
    rank: "37th",
    managementRank: "39th",
    year: 2023,
    name: "Amity University",
    location: "Noida, Uttar Pradesh",
    duration: "2 Years",
    semesters: "4 Semesters",
    fee: "₹199,000",
  },
  {
    id: 2,
    logo: "https://upload.wikimedia.org/wikipedia/en/1/1d/Kurukshetra_University_logo.png",
    emiPlan: true,
    image: "https://ku.digitaluniversity.ac/user/pages/images/slides/s3.jpg",
    rating: "A++",
    naac: "NAAC",
    creditPoints: "96+",
    rank: "151st",
    managementRank: "101st",
    year: 2024,
    name: "Kurukshetra University",
    location: "Kurukshetra, India",
    duration: "2",
    semesters: "4 Semesters",
    fee: "90,000",
  },
  {
    id: 3,
    logo: "https://i.pinimg.com/736x/c9/12/d4/c912d49f5f63e3c25aae2465f7577e7a.jpg",
    emiPlan: true,
    image:
      "https://images.shiksha.com/mediadata/images/articles/1655635763phpVQHm5C.jpeg",
    rating: "A++",
    naac: "NAAC",
    creditPoints: "102",
    rank: "38th",
    managementRank: "",
    year: 2024,
    name: "Lovely Professional University",
    location: "Jalandhar, Punjab",
    duration: "2 Years",
    semesters: "4 Semesters",
    fee: "₹145,600",
  },
  {
    id: 4,
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5kW1QiwZI1mxMzldLk3AV3fhz6-Wmivebmw&s",
    emiPlan: true,
    image: "https://admissionmentor.co.in/img/blog-img/jain.jpg",
    rating: "A++",
    naac: "NAAC",
    creditPoints: "90",
    rank: "68th",
    managementRank: "77th",
    year: 2024,
    name: "Jain University",
    location: "Jayanagar, Bangalore",
    duration: "2 Years",
    semesters: "4 Semesters",
    fee: "₹200,000",
  },
  {
    id: 5,
    logo: "https://doonmanagementschool.in/wp-content/uploads/2023/04/University-logo-new-oct-scaled-1.jpg",
    emiPlan: true,
    image: "https://www.uudoon.in/about/images/about-image-1.jpg",
    rating: "A+",
    naac: "NAAC",
    creditPoints: "80+",
    rank: "200th",
    managementRank: "105th",
    year: 2024,
    name: "Uttaranchal University",
    location: "Dehradun, Uttarakhand",
    duration: "2 Years",
    semesters: "4 Semesters",
    fee: "₹92,000",
  },
  {
    id: 6,
    logo: "https://upload.wikimedia.org/wikipedia/en/4/42/GLA_University_logo.png",
    emiPlan: true,
    image: "https://www.gla.ac.in/images/institute-overview.jpg",
    rating: "A+",
    naac: "NAAC",
    creditPoints: "110",
    rank: "101st",
    managementRank: "101st",
    year: 2025,
    name: "GLA University",
    location: "Mathura, India",
    duration: "2 Years",
    semesters: "4 Semesters",
    fee: "₹90,000",
  },
  {
    id: 7,
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-Mx5Ca8jO1s4RjWBQKke3YPNGUsLU2KCrMA&s",
    emiPlan: true,
    image:
      "https://blogger.googleusercontent.com/img/a/AVvXsEhhTgvVUO5-bFLFJXtTovOE_f4gMjD1ACVzTfZNKtZonYTe77nV8dSeymhqePAkIFqdKMMvTcAfyFyE2KHVdn5E2wlmQM2y_4ukcw-1Op7EE60jOXY-2qwAqSXvThKC8ldt6LLcdOUYLMNyQvQyXeNT5YEq590_0Nq_frXh9WzPEmUx55T1Ufyj-SLkfw=s16000",
    rating: "A+",
    naac: "NAAC",
    creditPoints: "80",
    rank: "20th",
    managementRank: "36th",
    year: 2025,
    name: "Chandigarh University",
    location: "Mohali, India",
    duration: "2 Years",
    semesters: "4 Semesters",
    fee: "₹200,000",
  },
];
export const universityCatalogCardData = [
  {
    id: 1,
    logo: "https://upload.wikimedia.org/wikipedia/en/f/ff/Amity_University_logo.png",
    emiPlan: true,
    image:
      "https://www.learningroutes.in/_next/image?url=https%3A%2F%2Faskusedu.com%2Fblogdashboard%2Fwp-content%2Fuploads%2F2024%2F04%2FAmity-Mohali.webp&w=1920&q=75",
    rating: "A+",
    naac: "NAAC",
    creditPoints: "90+",
    rank: "37th",
    managementRank: "39th",
    year: 2023,
    name: "Amity University",
    location: "Noida, Uttar Pradesh",
    duration: "2 Years",
    semesters: "4 Semesters",
    fee: "₹199,000",
  },
  {
    id: 2,
    logo: "https://upload.wikimedia.org/wikipedia/en/1/1d/Kurukshetra_University_logo.png",
    emiPlan: true,
    image: "https://ku.digitaluniversity.ac/user/pages/images/slides/s3.jpg",
    rating: "A++",
    naac: "NAAC",
    creditPoints: "96+",
    rank: "151st",
    managementRank: "101st",
    year: 2024,
    name: "Kurukshetra University",
    location: "Kurukshetra, India",
    duration: "2",
    semesters: "4 Semesters",
    fee: "90,000",
  },
  {
    id: 3,
    logo: "https://i.pinimg.com/736x/c9/12/d4/c912d49f5f63e3c25aae2465f7577e7a.jpg",
    emiPlan: true,
    image:
      "https://images.shiksha.com/mediadata/images/articles/1655635763phpVQHm5C.jpeg",
    rating: "A++",
    naac: "NAAC",
    creditPoints: "102",
    rank: "38th",
    managementRank: "",
    year: 2024,
    name: "Lovely Professional University",
    location: "Jalandhar, Punjab",
    duration: "2 Years",
    semesters: "4 Semesters",
    fee: "₹145,600",
  },
  {
    id: 4,
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5kW1QiwZI1mxMzldLk3AV3fhz6-Wmivebmw&s",
    emiPlan: true,
    image: "https://admissionmentor.co.in/img/blog-img/jain.jpg",
    rating: "A++",
    naac: "NAAC",
    creditPoints: "90",
    rank: "68th",
    managementRank: "77th",
    year: 2024,
    name: "Jain University",
    location: "Jayanagar, Bangalore",
    duration: "2 Years",
    semesters: "4 Semesters",
    fee: "₹200,000",
  },
  {
    id: 5,
    logo: "https://doonmanagementschool.in/wp-content/uploads/2023/04/University-logo-new-oct-scaled-1.jpg",
    emiPlan: true,
    image: "https://www.uudoon.in/about/images/about-image-1.jpg",
    rating: "A+",
    naac: "NAAC",
    creditPoints: "80+",
    rank: "200th",
    managementRank: "105th",
    year: 2024,
    name: "Uttaranchal University",
    location: "Dehradun, Uttarakhand",
    duration: "2 Years",
    semesters: "4 Semesters",
    fee: "₹92,000",
  },
  {
    id: 6,
    logo: "https://upload.wikimedia.org/wikipedia/en/4/42/GLA_University_logo.png",
    emiPlan: true,
    image: "https://www.gla.ac.in/images/institute-overview.jpg",
    rating: "A+",
    naac: "NAAC",
    creditPoints: "110",
    rank: "101st",
    managementRank: "101st",
    year: 2025,
    name: "GLA University",
    location: "Mathura, India",
    duration: "2 Years",
    semesters: "4 Semesters",
    fee: "₹90,000",
  },
  ,
  {
    id: 7,
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-Mx5Ca8jO1s4RjWBQKke3YPNGUsLU2KCrMA&s",
    emiPlan: true,
    image:
      "https://blogger.googleusercontent.com/img/a/AVvXsEhhTgvVUO5-bFLFJXtTovOE_f4gMjD1ACVzTfZNKtZonYTe77nV8dSeymhqePAkIFqdKMMvTcAfyFyE2KHVdn5E2wlmQM2y_4ukcw-1Op7EE60jOXY-2qwAqSXvThKC8ldt6LLcdOUYLMNyQvQyXeNT5YEq590_0Nq_frXh9WzPEmUx55T1Ufyj-SLkfw=s16000",
    rating: "A+",
    naac: "NAAC",
    creditPoints: "80",
    rank: "20th",
    managementRank: "36th",
    year: 2025,
    name: "Chandigarh University",
    location: "Mohali, India",
    duration: "2 Years",
    semesters: "4 Semesters",
    fee: "₹200,000",
  },
  {
    id: 8,
    logo: "https://pbs.twimg.com/profile_images/887620877138907136/Zau4_WSX_400x400.jpg",
    emiPlan: true,
    image: "https://www.nmims.edu/images/gallery/navimumbai-campus/1.jpg",
    rating: "A+",
    naac: "NAAC",
    creditPoints: "58",
    rank: "84th",
    managementRank: "21st",
    year: 2024,
    name: "NMIMS",
    location: "Mumbai, Maharashtra",
    duration: "2 Years",
    semesters: "4 Semesters",
    fee: "₹400,000",
  },
  {
    id: 9,
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Amrita-vishwa-vidyapeetham-logo.svg/2560px-Amrita-vishwa-vidyapeetham-logo.svg.png",
    emiPlan: true,
    image:
      "https://images.shiksha.com/mediadata/images/articles/1587994716phpmjYKDq.jpeg",
    rating: "A++",
    naac: "NAAC",
    creditPoints: "",
    rank: "7th",
    managementRank: "",
    year: 2024,
    name: "Amrita Vishwa Vidyapeetham",
    location: "Coimbatore, Tamil Nadu",
    duration: "2 Years",
    semesters: "4 Semesters",
    fee: "₹400,000",
  },
  {
    id: 10,
    logo: "https://i.pinimg.com/736x/35/4e/41/354e41b970004cac05cbe77bbc681ad8.jpg",
    emiPlan: true,
    image:
      "https://paruluniversity.ac.in/app/images/post/blog/featured_image/412491Gate%20Picture%20(1).jpg",
    rating: "A",
    naac: "NAAC",
    creditPoints: "",
    rank: "N/A",
    managementRank: "",
    year: 2024,
    name: "Parul University ",
    location: "Vadodara, Gujarat",
    duration: "2 Years",
    semesters: "4 Semesters",
    fee: "₹250,000",
  },
  {
    id: 11,
    logo: "https://online.shooliniuniversity.com/distance/assets/img/logo.png",
    emiPlan: true,
    image:
      "https://distanceeducationschool.com/wp-content/uploads/2024/05/university-page-shoolini-DES.webp",
    rating: "A",
    naac: "NAAC",
    creditPoints: "",
    rank: "N/A",
    managementRank: "",
    year: 2024,
    name: "Shoolini University ",
    location: "Solan, Himachal Pradesh",
    duration: "2 Years",
    semesters: "4 Semesters",
    fee: "₹200,000",
  },
  {
    id: 12,
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTK4Pd52Bzy8GLLUsBcY91yPN0VFzkERuN7-g&s",
    emiPlan: true,
    image:
      "https://media.collegedekho.com/media/img/institute/crawled_images/1496464164Sharda800x414.jpg",
    rating: "A+",
    naac: "NAAC",
    creditPoints: "",
    rank: "N/A",
    managementRank: "",
    year: 2024,
    name: "Sharda University ",
    location: "Greater Noida, Uttar Pradesh",
    duration: "2 Years",
    semesters: "4 Semesters",
    fee: "₹300,000",
  },
  {
    id: 13,
    logo: "https://content.jdmagicbox.com/comp/dehradun/w1/9999pd135.d135.110721154744.r1w1/catalogue/sikkim-manipal-university-toll-free-no-dehradun-gpo-dehradun-institutes-for-disaster-management-klht5.jpg",
    emiPlan: true,
    image:
      "https://argroupofeducation.com/wp-content/uploads/2024/02/Sikkim-Manipal-University2.jpg",
    rating: "A",
    naac: "NAAC",
    creditPoints: "",
    rank: "N/A",
    managementRank: "",
    year: 2024,
    name: "Sikkim Manipal University",
    location: "Sikkim, India",
    duration: "2 Years",
    semesters: "4 Semesters",
    fee: "₹280,000",
  },
  {
    id: 14,
    logo: "https://indiaeducationdiary.in/wp-content/uploads/2022/01/UPES-LOGO-01.jpg?w=640",
    emiPlan: true,
    image:
      "https://collegewaale.com/upes/wp-content/uploads/2023/12/upes-1-1024x768.webp",
    rating: "A",
    naac: "NAAC",
    creditPoints: "",
    rank: "N/A",
    managementRank: "",
    year: 2024,
    name: "UPES ",
    location: "Dehradun, Uttarakhand",
    duration: "2 Years",
    semesters: "4 Semesters",
    fee: "₹320,000",
  },
  {
    id: 15,
    logo: "https://content.jdmagicbox.com/v2/comp/hyderabad/64/040p7005064/catalogue/vignan-institute-of-technology-and-science-kukatpally-hyderabad-engineering-colleges-pe113r.jpg",
    emiPlan: true,
    image: "https://vignan.ac.in/images/apex/5.jpg",
    rating: "A",
    naac: "NAAC",
    creditPoints: "",
    rank: "N/A",
    managementRank: "",
    year: 2024,
    name: "Vignan's University",
    location: "Guntur, Andhra Pradesh",
    duration: "2 Years",
    semesters: "4 Semesters",
    fee: "₹270,000",
  },
  {
    id: 16,
    logo: "https://upload.wikimedia.org/wikipedia/commons/8/8f/Vivekananda-global-university-jaipur.jpg",
    emiPlan: true,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLM3_HyshA0jjzj3r7qnynSwaiVVCsUnld6A&s",
    rating: "B+",
    naac: "NAAC",
    creditPoints: "",
    rank: "Top 45",
    managementRank: "",
    year: 2024,
    name: "Vivekananda Global University",
    location: "Jaipur, Rajasthan",
    duration: "2 Years",
    semesters: "4 Semesters",
    fee: "₹250,000",
  },
  {
    id: 17,
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQskJ0c3dzaabVW_PWcxTUViMR2PQmpHOKfJg&s",
    emiPlan: true,
    image:
      "https://www.guidanceforever.org/wp-content/uploads/2023/10/aligarh-muslim-university-aligarh-featured-2.jpg",
    rating: "A+",
    naac: "NAAC",
    creditPoints: "",
    rank: "Top 5",
    managementRank: "",
    year: 2024,
    name: "Aligarh Muslim University",
    location: "Aligarh, Uttar Pradesh",
    duration: "2 Years",
    semesters: "4 Semesters",
    fee: "₹220,000",
  },
  // {
  //   id: 18,
  //   logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAMJ1BwQisVClB5CvBgI40-5Y0ZJkgyYqT3g&s",
  //   emiPlan: true,
  //   image:
  //     "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQACYdQibAiUDHvxht7JsHRtXaqJFjokIgB7w&s",
  //   rating: "A+",
  //   naac: "NAAC",
  //   creditPoints: "",
  //   rank: "Top 10",
  //   managementRank: "",
  //   year: 2024,
  //   name: "Andhra University",
  //   location: "Visakhapatnam, Andhra Pradesh",
  //   duration: "2 Years",
  //   semesters: "4 Semesters",
  //   fee: "₹180,000",
  // },
  {
    id: 19,
    logo: "https://static.wixstatic.com/media/bff831_b2037f9baf424ffeb229a275ab3da890~mv2.png/v1/fill/w_518,h_222,al_c,lg_1,q_85,enc_avif,quality_auto/dyp-online-logo.png",
    emiPlan: true,
    image:
      "https://gcetl.in/web2manage/images/Universities/University1719920235dyn%20patil.jpg",
    rating: "A",
    naac: "NAAC",
    creditPoints: "",
    rank: "Top 15",
    managementRank: "",
    year: 2024,
    name: "D.Y. Patil University",
    location: "Navi Mumbai, Maharashtra",
    duration: "2 Years",
    semesters: "4 Semesters",
    fee: "₹200,000",
  },
  {
    id: 20,
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFphxje5ISCTbvjGYFf7rCUIElnSbP9ovxpg&s",
    emiPlan: true,
    image:
      "https://www.manipaldubai.com/_next/image?url=https%3A%2F%2Fmanipalblobstorage.blob.core.windows.net%2Fmanipal-azr-container%2F%2F002_Institute_MUJ_1_jpg_1296x700_3653573dc5.webp&w=1920&q=75",
    rating: "A++",
    naac: "NAAC",
    creditPoints: "",
    rank: "Top 5",
    managementRank: "",
    year: 2024,
    name: "Manipal University",
    location: "Manipal, Karnataka",
    duration: "2 Years",
    semesters: "4 Semesters",
    fee: "₹450,000",
  },
  {
    id: 21,
    logo: "https://upload.wikimedia.org/wikipedia/commons/8/87/Dr._D._Y._Patil_Medical_College%2C_Hospital_%26_Research_Centre_logo.jpg",
    emiPlan: true,
    image:
      "https://sardarpateleducation.com/wp-content/uploads/2025/02/Infrastructure-01-1.jpg",
    rating: "A++",
    naac: "NAAC",
    creditPoints: "",
    rank: "Top 10",
    managementRank: "",
    year: 2024,
    name: "Dr. D. Y. Patil Vidyapeeth University (DPU)",
    location: "Pune, Maharashtra",
    duration: "2 Years",
    semesters: "4 Semesters",
    fee: "₹210,000",
  },
  {
    id: 22,
    logo: "https://jamiahamdard.edu/images/top-logo.png",
    emiPlan: true,
    image: "https://jamiahamdard.edu/images/explore-kings-accommodation.jpg",
    rating: "A",
    naac: "NAAC",
    creditPoints: "",
    rank: "Top 20",
    managementRank: "",
    year: 2024,
    name: "Jamia Hamdard University",
    location: "New Delhi",
    duration: "2 Years",
    semesters: "4 Semesters",
    fee: "₹190,000",
  },
  {
    id: 23,
    logo: "https://www.yugedu.com/media/654/mizoram-university-online-logo.png",
    emiPlan: true,
    image:
      "https://image-static.collegedunia.com/public/college_data/images/appImage/1513313634adminbuilding02.jpg?h=260&w=360&mode=crop",
    rating: "A",
    naac: "NAAC",
    creditPoints: "",
    rank: "Top 25",
    managementRank: "",
    year: 2024,
    name: "Mizoram University",
    location: "Aizawl, Mizoram",
    duration: "2 Years",
    semesters: "4 Semesters",
    fee: "₹170,000",
  },
];

export const universityDetailData = {
  1: {
    id: 1,
    name: "Amity University",
    location: "Noida, Uttar Pradesh",
    description:
      "Amity University, Noida is a private research university located in Noida, Uttar Pradesh, India. It was established in 2005 by an Act of the State Legislature of Uttar Pradesh. It has campuses in India and overseas branch campuses in Dubai and Tashkent.",
    image:
      "https://www.learningroutes.in/_next/image?url=https%3A%2F%2Faskusedu.com%2Fblogdashboard%2Fwp-content%2Fuploads%2F2024%2F04%2FAmity-Mohali.webp&w=1920&q=75",
    logo: "https://upload.wikimedia.org/wikipedia/en/f/ff/Amity_University_logo.png",
    year: 2023,
    naac: "A+",
    rank: "37th",
    founded: 2005,
    creditPoints: "90+",
    semesters: 4,
    duration: "2 Years",
    course: "Online MBA",
    semesterFees: "₹49,750",
    applicationFees: "₹1,100",
    totalFees: "₹199,000",
    emiPlan: true,
  },
  2: {
    id: 2,
    name: "Kurukshetra University",
    location: "Kurukshetra, India",
    description:
      "Kurukshetra University, Kurukshetra is a university established on 11 January 1956 in Kurukshetra, in the Indian state of Haryana, 160 kilometres from the capital, Delhi. It is a member of Association of Commonwealth Universities.",
    image: "https://ku.digitaluniversity.ac/user/pages/images/slides/s3.jpg",
    logo: "https://upload.wikimedia.org/wikipedia/en/1/1d/Kurukshetra_University_logo.png",
    year: 2024,
    naac: "A++",
    rank: "151st",
    founded: 1956,
    creditPoints: "96",
    semesters: 4,
    duration: "2 Years",
    course: "Online MBA",
    semesterFees: "₹22,500",
    applicationFees: "₹1,000",
    totalFees: "₹90,000",
    emiPlan: true,
  },
  3: {
    id: 3,
    name: "Lovely Professional University",
    location: "Jalandhar, Punjab",
    description:
      "Lovely Professional University is a private university located in Chaheru, Phagwara, Punjab, India. The university was established in 2005 by Lovely International Trust, through the Lovely Professional University Act, 2005 and started operation in 2006.",
    image:
      "https://images.shiksha.com/mediadata/images/articles/1655635763phpVQHm5C.jpeg",
    logo: "https://i.pinimg.com/736x/c9/12/d4/c912d49f5f63e3c25aae2465f7577e7a.jpg",
    year: 2024,
    naac: "A++",
    rank: "38th",
    founded: 2005,
    creditPoints: "102",
    semesters: 4,
    duration: "2 Years",
    course: "Online MBA",
    semesterFees: "₹36,400",
    applicationFees: "₹600",
    totalFees: "₹145,600",
    emiPlan: true,
  },
  4: {
    id: 4,
    name: "Jain University",
    location: "Jayanagar, Bangalore",
    description:
      "JAIN is a private deemed university in Bengaluru, India. Originating from Sri Bhagawan Mahaveer Jain College of Engineering, it was conferred the deemed-to-be-university status in 2009. In August 2019, Jain University opened its off-campus in Kochi, Kerala.",
    image: "https://admissionmentor.co.in/img/blog-img/jain.jpg",
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5kW1QiwZI1mxMzldLk3AV3fhz6-Wmivebmw&s",
    year: 2024,
    naac: "A++",
    rank: "68th",
    founded: 1990,
    creditPoints: "90",
    semesters: 4,
    duration: "2 Years",
    course: "Online MBA",
    semesterFees: "₹49,000",
    applicationFees: "₹2,500",
    totalFees: "₹200,000",
    emiPlan: true,
  },
  5: {
    id: 5,
    name: "Uttaranchal University",
    location: "Dehradun, Uttarakhand",
    description:
      "Uttaranchal University is an academic cum research university located at Dehradun, Uttarakhand, India near Indian Military Academy. It was established by an Act of the Uttarakhand Legislative Assembly under Smt Shushila Devi Education Foundation.",
    image: "https://www.uudoon.in/about/images/about-image-1.jpg",
    logo: "https://doonmanagementschool.in/wp-content/uploads/2023/04/University-logo-new-oct-scaled-1.jpg",
    year: 2024,
    naac: "A+",
    rank: "200th",
    founded: 2013,
    creditPoints: "80+",
    semesters: 4,
    duration: "2 Years",
    course: "Online MBA",
    semesterFees: "₹20,500",
    applicationFees: "₹0",
    totalFees: "₹92,000",
    emiPlan: true,
  },
  6: {
    id: 6,
    name: "GLA University",
    location: "Mathura, India",
    description:
      "GLA University is a private university in Mathura, Uttar Pradesh. It is recognized by University Grants Commission, NCTE and Pharmacy Council of India. It has been accredited by the National Assessment and Accreditation Council with ‘A+’ Grade.",
    image: "https://www.gla.ac.in/images/institute-overview.jpg",
    logo: "https://upload.wikimedia.org/wikipedia/en/4/42/GLA_University_logo.png",
    year: 2025,
    naac: "A+",
    rank: "101st",
    founded: 2010,
    creditPoints: "110",
    semesters: 4,
    duration: "2 Years",
    course: "Online MBA",
    semesterFees: "₹24,000",
    applicationFees: "₹1,000",
    totalFees: "₹90,000",
    emiPlan: true,
  },
  7: {
    id: 7,
    name: "Chandigarh University",
    location: "Mohali, India",
    description:
      "Chandigarh University (CU) is a private university located in Mohali, India. The university was established on 10 July 2012 by an act of Punjab State Legislature. It is recognized by University Grants Commission under Section 2(f) with the right to confer degrees as per Section 22(1) of the UGC Act, 1956.",
    image:
      "https://blogger.googleusercontent.com/img/a/AVvXsEhhTgvVUO5-bFLFJXtTovOE_f4gMjD1ACVzTfZNKtZonYTe77nV8dSeymhqePAkIFqdKMMvTcAfyFyE2KHVdn5E2wlmQM2y_4ukcw-1Op7EE60jOXY-2qwAqSXvThKC8ldt6LLcdOUYLMNyQvQyXeNT5YEq590_0Nq_frXh9WzPEmUx55T1Ufyj-SLkfw=s16000",
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-Mx5Ca8jO1s4RjWBQKke3YPNGUsLU2KCrMA&s",
    year: 2024,
    naac: "A+",
    rank: "20th",
    founded: "N/A",
    creditPoints: "80",
    semesters: 4,
    duration: "2 Years",
    course: "Online MBA",
    semesterFees: "₹37,500",
    applicationFees: "₹0",
    totalFees: "₹200,000",
    emiPlan: true,
  },
  8: {
    id: 8,
    name: "Narsee Monjee Institute of Management Studies",
    location: "Mumbai, Maharashtra",
    description:
      "Shri Vile Parle Kelavani Mandal's Narsee Monjee Institute of Management Studies (abbreviated as SVKM's NMIMS) is a private deemed university located in Mumbai. It has 17 constituent schools that offer both undergraduate and postgraduate courses in management, engineering, commerce, pharmacy, architecture, economics, mathematical sciences, hospitality, science, law, aviation, liberal arts, performing arts, architecture & design.",
    image: "https://www.nmims.edu/images/gallery/navimumbai-campus/1.jpg",
    logo: "https://pbs.twimg.com/profile_images/887620877138907136/Zau4_WSX_400x400.jpg",
    year: 2024,
    naac: "A+",
    rank: "84th",
    founded: 1981,
    creditPoints: 58,
    semesters: 4,
    duration: "2 Years",
    course: "Executive MBA",
    semesterFees: "₹100,000",
    applicationFees: "₹1,500",
    totalFees: "₹400,000",
    emiPlan: true,
  },
  9: {
    id: 9,
    name: "Amrita Vishwa Vidyapeetham",
    location: "Coimbatore, Tamil Nadu",
    description:
      "Amrita Vishwa Vidyapeetham is a multi-campus, multi-disciplinary research university in India, known for its high-quality education and research across various fields.",
    image:
      "https://images.shiksha.com/mediadata/images/articles/1587994716phpmjYKDq.jpeg",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Amrita-vishwa-vidyapeetham-logo.svg/2560px-Amrita-vishwa-vidyapeetham-logo.svg.png",
    year: 2023,
    naac: "A++",
    rank: "5th",
    founded: 2003,
    creditPoints: "90+",
    semesters: 4,
    duration: "2 Years",
    course: "Online MBA",
    semesterFees: "₹50,000",
    applicationFees: "₹1,000",
    totalFees: "₹200,000",
    emiPlan: true,
  },
  10: {
    id: 10,
    name: "Parul University",
    location: "Vadodara, Gujarat",
    description:
      "Parul University is a private university offering a wide range of undergraduate and postgraduate programs across various disciplines.",
    image:
      "https://i.pinimg.com/736x/35/4e/41/354e41b970004cac05cbe77bbc681ad8.jpg",
    logo: "https://paruluniversity.ac.in/pu-content/uploads/2021/12/pu-logo.png",
    year: 2023,
    naac: "A+",
    rank: "45th",
    founded: 2015,
    creditPoints: "90+",
    semesters: 4,
    duration: "2 Years",
    course: "Online MBA",
    semesterFees: "₹45,000",
    applicationFees: "₹1,000",
    totalFees: "₹180,000",
    emiPlan: true,
  },
  11: {
    id: 11,
    name: "Shoolini University",
    location: "Solan, Himachal Pradesh",
    description:
      "Shoolini University is a research-driven private university recognized for its focus on innovation, quality placements, and academic excellence.",
    image: " https://distanceeducationschool.com/wp-content/uploads/2024/05/university-page-shoolini-DES.webp",
    logo: " https://online.shooliniuniversity.com/distance/assets/img/logo.png",
    year: 2023,
    naac: "A+",
    rank: "73rd",
    founded: 2009,
    creditPoints: "90+",
    semesters: 4,
    duration: "2 Years",
    course: "Online MBA",
    semesterFees: "₹50,000",
    applicationFees: "₹1,200",
    totalFees: "₹200,000",
    emiPlan: true,
  },
  12: {
    id: 12,
    name: "Sharda University",
    location: "Greater Noida, Uttar Pradesh",
    description:
      "Sharda University is a leading educational institution offering a wide range of undergraduate and postgraduate programs with a focus on holistic development.",
    image:
      "https://media.collegedekho.com/media/img/institute/crawled_images/1496464164Sharda800x414.jpg",
    logo: " https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTK4Pd52Bzy8GLLUsBcY91yPN0VFzkERuN7-g&s",
    year: 2023,
    naac: "A",
    rank: "151-200th",
    founded: 2009,
    creditPoints: "90+",
    semesters: 4,
    duration: "2 Years",
    course: "Online MBA",
    semesterFees: "₹47,500",
    applicationFees: "₹1,000",
    totalFees: "₹190,000",
    emiPlan: true,
  },
  13: {
    id: 13,
    name: "Sikkim Manipal University",
    location: "Gangtok, Sikkim",
    description:
      "Sikkim Manipal University offers quality education in various disciplines and is known for its distance education programs.",
    image: " https://argroupofeducation.com/wp-content/uploads/2024/02/Sikkim-Manipal-University2.jpg",
    logo: "https://content.jdmagicbox.com/comp/dehradun/w1/9999pd135.d135.110721154744.r1w1/catalogue/sikkim-manipal-university-toll-free-no-dehradun-gpo-dehradun-institutes-for-disaster-management-klht5.jpg",
    year: 2023,
    naac: "A+",
    rank: "101-150th",
    founded: 1995,
    creditPoints: "90+",
    semesters: 4,
    duration: "2 Years",
    course: "Distance MBA",
    semesterFees: "₹42,500",
    applicationFees: "₹1,000",
    totalFees: "₹170,000",
    emiPlan: true,
  },
  14: {
    id: 14,
    name: "UPES",
    location: "Dehradun, Uttarakhand",
    description:
      "UPES is a multidisciplinary university known for its industry-aligned programs and emphasis on holistic development.",
    image: " https://collegewaale.com/upes/wp-content/uploads/2023/12/upes-1-1024x768.webp",
    logo: " https://indiaeducationdiary.in/wp-content/uploads/2022/01/UPES-LOGO-01.jpg?w=640",
    year: 2023,
    naac: "A",
    rank: "46th",
    founded: 2003,
    creditPoints: "90+",
    semesters: 4,
    duration: "2 Years",
    course: "Online MBA",
    semesterFees: "₹52,000",
    applicationFees: "₹1,350",
    totalFees: "₹208,000",
    emiPlan: true,
  },
  15: {
    id: 15,
    name: "Vignan's University",
    location: "Guntur, Andhra Pradesh",
    description:
      "Vignan's University is a private university offering a variety of undergraduate and postgraduate programs with a focus on engineering and technology.",
    image: " https://vignan.ac.in/images/apex/5.jpg",
    logo: "https://content.jdmagicbox.com/v2/comp/hyderabad/64/040p7005064/catalogue/vignan-institute-of-technology-and-science-kukatpally-hyderabad-engineering-colleges-pe113r.jpg",
    year: 2023,
    naac: "A+",
    rank: "95th",
    founded: 2008,
    creditPoints: "90+",
    semesters: 4,
    duration: "2 Years",
    course: "Online MBA",
    semesterFees: "₹48,000",
    applicationFees: "₹1,000",
    totalFees: "₹192,000",
    emiPlan: true,
  },
  16: {
    id: 16,
    name: "Vivekananda Global University",
    location: "Jaipur, Rajasthan",
    description:
      "Vivekananda Global University (VGU) is a private university located in Jaipur, Rajasthan. It is known for its focus on research, innovation, and entrepreneurship across various disciplines including engineering, management, law, and design.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLM3_HyshA0jjzj3r7qnynSwaiVVCsUnld6A&s",
    logo: "https://upload.wikimedia.org/wikipedia/commons/8/8f/Vivekananda-global-university-jaipur.jpg",
    year: 2023,
    naac: "A+",
    rank: "56th",
    founded: 2012,
    creditPoints: "90+",
    semesters: 4,
    duration: "2 Years",
    course: "Online MBA",
    semesterFees: "₹37,500",
    applicationFees: "₹1,000",
    totalFees: "₹150,000",
    emiPlan: true,
  },
  17: {
    id: 17,
    name: "Aligarh Muslim University",
    location: "Aligarh, Uttar Pradesh",
    description:
      "Aligarh Muslim University (AMU) is a public central university in Aligarh, Uttar Pradesh, India. Established in 1920, it originated from the Mohammedan Anglo-Oriental College set up by Sir Syed Ahmed Khan in 1875. AMU offers more than 300 courses in both traditional and modern branches of education.",
    image: " https://www.guidanceforever.org/wp-content/uploads/2023/10/aligarh-muslim-university-aligarh-featured-2.jpg",
    logo: " https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQskJ0c3dzaabVW_PWcxTUViMR2PQmpHOKfJg&s",
    year: 2023,
    naac: "A+",
    rank: "10th",
    founded: 1920,
    creditPoints: "Varies",
    semesters: 4,
    duration: "2 Years",
    course: "MBA",
    semesterFees: "₹50,000",
    applicationFees: "₹650",
    totalFees: "₹200,000",
    emiPlan: false,
  },
  // 18: {
  //   id: 18,
  //   name: "Andhra University",
  //   location: "Visakhapatnam, Andhra Pradesh",
  //   description:
  //     "Andhra University is a public university located in Visakhapatnam, Andhra Pradesh, India. Established in 1926, it is one of the oldest universities in India and offers a wide range of undergraduate and postgraduate programs.",
  //   image:" https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQACYdQibAiUDHvxht7JsHRtXaqJFjokIgB7w&s",
  //   logo: " https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAMJ1BwQisVClB5CvBgI40-5Y0ZJkgyYqT3g&s",
  //   year: 2023,
  //   naac: "A++",
  //   rank: "36th",
  //   founded: 1926,
  //   creditPoints: "Varies",
  //   semesters: 4,
  //   duration: "2 Years",
  //   course: "MBA",
  //   semesterFees: "₹30,000",
  //   applicationFees: "₹500",
  //   totalFees: "₹120,000",
  //   emiPlan: false,
  // },
  19: {
    id: 19,
    name: "D.Y. Patil University",
    location: "Navi Mumbai, Maharashtra",
    description:
      "D.Y. Patil University is a private university located in Navi Mumbai, Maharashtra, India. It offers a variety of undergraduate and postgraduate programs across disciplines such as medicine, dentistry, engineering, management, and more.",
    image:
      "https://gcetl.in/web2manage/images/Universities/University1719920235dyn%20patil.jpg",
    logo: "https://static.wixstatic.com/media/bff831_b2037f9baf424ffeb229a275ab3da890~mv2.png/v1/fill/w_518,h_222,al_c,lg_1,q_85,enc_avif,quality_auto/dyp-online-logo.png",
    year: 2023,
    naac: "A",
    rank: "Not Ranked",
    founded: 2002,
    creditPoints: "Varies",
    semesters: 4,
    duration: "2 Years",
    course: "MBA",
    semesterFees: "₹60,000",
    applicationFees: "₹1,000",
    totalFees: "₹240,000",
    emiPlan: true,
  },
  20: {
    id: 20,
    name: "Manipal University",
    location: "Manipal, Karnataka",
    description:
      "Manipal Academy of Higher Education (MAHE), commonly known as Manipal University, is a top-ranked private deemed university with a legacy of excellence in education. Known for its high-quality academic programs and global collaborations, it offers various online and distance learning courses including an Online MBA.",
    image:
      "https://www.manipaldubai.com/_next/image?url=https%3A%2F%2Fmanipalblobstorage.blob.core.windows.net%2Fmanipal-azr-container%2F%2F002_Institute_MUJ_1_jpg_1296x700_3653573dc5.webp&w=1920&q=75",
    logo: " https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFphxje5ISCTbvjGYFf7rCUIElnSbP9ovxpg&s",
    year: 2023,
    naac: "A++",
    rank: "6th",
    founded: 1953,
    creditPoints: "90+",
    semesters: 4,
    duration: "2 Years",
    course: "Online MBA",
    semesterFees: "₹37,500",
    applicationFees: "₹500",
    totalFees: "₹150,000",
    emiPlan: true,
  },
  21: {
    id: 21,
    name: "Dr. D. Y. Patil Vidyapeeth University (DPU)",
    location: "Pune, Maharashtra",
    description:
      "Dr. D. Y. Patil Vidyapeeth, Pune, is a deemed-to-be university offering a range of undergraduate, postgraduate, and doctoral programs. It is well known for its medical, management, and online education offerings with a focus on innovation and research.",
    image: " https://sardarpateleducation.com/wp-content/uploads/2025/02/Infrastructure-01-1.jpg",
    logo: "https://upload.wikimedia.org/wikipedia/commons/8/87/Dr._D._Y._Patil_Medical_College%2C_Hospital_%26_Research_Centre_logo.jpg",
    year: 2023,
    naac: "A++",
    rank: "46th",
    founded: 2003,
    creditPoints: "90+",
    semesters: 4,
    duration: "2 Years",
    course: "Online MBA",
    semesterFees: "₹35,000",
    applicationFees: "₹500",
    totalFees: "₹140,000",
    emiPlan: true,
  },
  22: {
    id: 21,
    name: "Jamia Hamdard University",
    location: "New Delhi, Delhi",
    description:
      "Jamia Hamdard is a deemed-to-be university located in New Delhi, India. Established in 1989, it is renowned for its programs in pharmacy, medicine, nursing, allied health, and management.",
    image:
      " https://jamiahamdard.edu/images/explore-kings-accommodation.jpg",
    logo: "https://jamiahamdard.edu/images/top-logo.png",
    year: 2023,
    naac: "A",
    rank: "37th",
    founded: 1989,
    creditPoints: "Varies",
    semesters: 4,
    duration: "2 Years",
    course: "MBA",
    semesterFees: "₹70,000",
    applicationFees: "₹1,500",
    totalFees: "₹280,000",
    emiPlan: true,
  },
  23: {
    id: 22,
    name: "Mizoram University",
    location: "Aizawl, Mizoram",
    description:
      "Mizoram University is a central university established in 2001 in Aizawl, Mizoram, India. It offers various undergraduate and postgraduate programs across multiple disciplines.",
    image:
      " https://image-static.collegedunia.com/public/college_data/images/appImage/1513313634adminbuilding02.jpg?h=260&w=360&mode=crop",
    logo: " https://www.yugedu.com/media/654/mizoram-university-online-logo.png",
    year: 2023,
    naac: "A",
    rank: "76th",
    founded: 2001,
    creditPoints: "Varies",
    semesters: 4,
    duration: "2 Years",
    course: "MBA",
    semesterFees: "₹25,000",
    applicationFees: "₹700",
    totalFees: "₹100,000",
    emiPlan: false,
  },
};
