export const universityCardData = [
    {
      id: 1,
      logo: "https://upload.wikimedia.org/wikipedia/en/f/ff/Amity_University_logo.png",
      emiPlan: true,
      image:
        "https://www.learningroutes.in/_next/image?url=https%3A%2F%2Faskusedu.com%2Fblogdashboard%2Fwp-content%2Fuploads%2F2024%2F04%2FAmity-Mohali.webp&w=1920&q=75",
      rating: "A+",
      naac: "NAAC",
      creditPoints: "90+",
      rank: "37th",
      managementRank: "39th",
      year: 2023,
      name: "Amity University",
      location: "Noida, Uttar Pradesh",
      duration: "2 Years",
      semesters: "4 Semesters",
      fee: "₹199,000",
    },
    {
      id: 2,
      logo: "https://upload.wikimedia.org/wikipedia/en/1/1d/Kurukshetra_University_logo.png",
      emiPlan: true,
      image:
        "https://ku.digitaluniversity.ac/user/pages/images/slides/s3.jpg",
      rating: "A++",
      naac: "NAAC",
      creditPoints: "96+",
      rank: "151st",
      managementRank: "101st",
      year: 2024,
      name: "Kurukshetra University",
      location: "Kurukshetra, India",
      duration: "2",
      semesters: "4 Semesters",
      fee: "90,000",
    },
    {
      id: 3,
      logo: "https://i.pinimg.com/736x/c9/12/d4/c912d49f5f63e3c25aae2465f7577e7a.jpg",
      emiPlan: true,
      image: "https://images.shiksha.com/mediadata/images/articles/1655635763phpVQHm5C.jpeg",
      rating: "A++",
      naac: "NAAC",
      creditPoints: "102",
      rank: "38th",
      managementRank: "",
      year: 2024,
      name: "Lovely Professional University",
      location: "Jalandhar, Punjab",
      duration: "2 Years",
      semesters: "4 Semesters",
      fee: "₹145,600"
  },
  {
    id: 4,
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5kW1QiwZI1mxMzldLk3AV3fhz6-Wmivebmw&s",
    emiPlan: true,
    image: "https://admissionmentor.co.in/img/blog-img/jain.jpg",
    rating: "A++",
    naac: "NAAC",
    creditPoints: "90",
    rank: "68th",
    managementRank: "77th",
    year: 2024,
    name: "Jain University",
    location: "Jayanagar, Bangalore",
    duration: "2 Years",
    semesters: "4 Semesters",
    fee: "₹200,000"
  }
  ,
  {
      id: 5,
      logo: "https://doonmanagementschool.in/wp-content/uploads/2023/04/University-logo-new-oct-scaled-1.jpg",
      emiPlan: true,
      image: "https://www.uudoon.in/about/images/about-image-1.jpg",
      rating: "A+",
      naac: "NAAC",
      creditPoints: "80+",
      rank: "200th",
      managementRank: "105th",
      year: 2024,
      name: "Uttaranchal University",
      location: "Dehradun, Uttarakhand",
      duration: "2 Years",
      semesters: "4 Semesters",
      fee: "₹92,000"
  },
  {
      id: 6,
      logo: "https://upload.wikimedia.org/wikipedia/en/4/42/GLA_University_logo.png",
      emiPlan: true,
      image: "https://www.gla.ac.in/images/institute-overview.jpg",
      rating: "A+",
      naac: "NAAC",
      creditPoints: "110",
      rank: "101st",
      managementRank: "101st",
      year: 2025,
      name: "GLA University",
      location: "Mathura, India",
      duration: "2 Years",
      semesters: "4 Semesters",
      fee: "₹90,000"
  },
  ,
  {
      id: 7,
      logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-Mx5Ca8jO1s4RjWBQKke3YPNGUsLU2KCrMA&s",
      emiPlan: true,
      image: "https://blogger.googleusercontent.com/img/a/AVvXsEhhTgvVUO5-bFLFJXtTovOE_f4gMjD1ACVzTfZNKtZonYTe77nV8dSeymhqePAkIFqdKMMvTcAfyFyE2KHVdn5E2wlmQM2y_4ukcw-1Op7EE60jOXY-2qwAqSXvThKC8ldt6LLcdOUYLMNyQvQyXeNT5YEq590_0Nq_frXh9WzPEmUx55T1Ufyj-SLkfw=s16000",
      rating: "A+",
      naac: "NAAC",
      creditPoints: "80",
      rank: "20th",
      managementRank: "36th",
      year: 2025,
      name: "Chandigarh University",
      location: "Mohali, India",
      duration: "2 Years",
      semesters: "4 Semesters",
      fee: "₹200,000"
  },
  {
      id: 8,
      logo: "https://pbs.twimg.com/profile_images/887620877138907136/Zau4_WSX_400x400.jpg",
      emiPlan: true,
      image: "https://www.nmims.edu/images/gallery/navimumbai-campus/1.jpg",
      rating: "A+",
      naac: "NAAC",
      creditPoints: "58",
      rank: "84th",
      managementRank: "21st",
      year: 2024,
      name: "NMIMS",
      location: "Mumbai, Maharashtra",
      duration: "2 Years",
      semesters: "4 Semesters",
      fee: "₹400,000"
  }
  ];

  export const universityDetailData = {
    1: {
      id: 1,
      name: "Amity University",
      location: "Noida, Uttar Pradesh",
      description: "Amity University, Noida is a private research university located in Noida, Uttar Pradesh, India. It was established in 2005 by an Act of the State Legislature of Uttar Pradesh. It has campuses in India and overseas branch campuses in Dubai and Tashkent.",
      image: "https://www.learningroutes.in/_next/image?url=https%3A%2F%2Faskusedu.com%2Fblogdashboard%2Fwp-content%2Fuploads%2F2024%2F04%2FAmity-Mohali.webp&w=1920&q=75",
      logo: "https://upload.wikimedia.org/wikipedia/en/f/ff/Amity_University_logo.png",
      year: 2023,
      naac: "A+",
      rank: "37th",
      founded: 2005,
      creditPoints: "90+",
      semesters: 4,
      duration: "2 Years",
      course: "Online MBA",
      semesterFees: "₹49,750",
      applicationFees: "₹1,100",
      totalFees: "₹199,000",
      emiPlan: true
  },
 2: {
    id: 2,
    name: "Kurukshetra University",
    location: "Kurukshetra, India",
    description: "Kurukshetra University, Kurukshetra is a university established on 11 January 1956 in Kurukshetra, in the Indian state of Haryana, 160 kilometres from the capital, Delhi. It is a member of Association of Commonwealth Universities.",
    image: "https://ku.digitaluniversity.ac/user/pages/images/slides/s3.jpg",
    logo: "https://upload.wikimedia.org/wikipedia/en/1/1d/Kurukshetra_University_logo.png",
    year: 2024,
    naac: "A++",
    rank: "151st",
    founded: 1956,
    creditPoints: "96",
    semesters: 4,
    duration: "2 Years",
    course: "Online MBA",
    semesterFees: "₹22,500",
    applicationFees: "₹1,000",
    totalFees: "₹90,000",
    emiPlan: true
},
3:{
  id: 3,
  name: "Lovely Professional University",
  location: "Jalandhar, Punjab",
  description: "Lovely Professional University is a private university located in Chaheru, Phagwara, Punjab, India. The university was established in 2005 by Lovely International Trust, through the Lovely Professional University Act, 2005 and started operation in 2006.",
  image: "https://images.shiksha.com/mediadata/images/articles/1655635763phpVQHm5C.jpeg",
  logo: "https://i.pinimg.com/736x/c9/12/d4/c912d49f5f63e3c25aae2465f7577e7a.jpg",
  year: 2024,
  naac: "A++",
  rank: "38th",
  founded: 2005,
  creditPoints: "102",
  semesters: 4,
  duration: "2 Years",
  course: "Online MBA",
  semesterFees: "₹36,400",
  applicationFees: "₹600",
  totalFees: "₹145,600",
  emiPlan: true
},
4:{
  id: 4,
  name: "Jain University",
  location: "Jayanagar, Bangalore",
  description: "JAIN is a private deemed university in Bengaluru, India. Originating from Sri Bhagawan Mahaveer Jain College of Engineering, it was conferred the deemed-to-be-university status in 2009. In August 2019, Jain University opened its off-campus in Kochi, Kerala.",
  image: "https://admissionmentor.co.in/img/blog-img/jain.jpg",
  logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5kW1QiwZI1mxMzldLk3AV3fhz6-Wmivebmw&s",
  year: 2024,
  naac: "A++",
  rank: "68th",
  founded: 1990,
  creditPoints: "90",
  semesters: 4,
  duration: "2 Years",
  course: "Online MBA",
  semesterFees: "₹49,000",
  applicationFees: "₹2,500",
  totalFees: "₹200,000",
  emiPlan: true
},
5:{
  id: 5,
  name: "Uttaranchal University",
  location: "Dehradun, Uttarakhand",
  description: "Uttaranchal University is an academic cum research university located at Dehradun, Uttarakhand, India near Indian Military Academy. It was established by an Act of the Uttarakhand Legislative Assembly under Smt Shushila Devi Education Foundation.",
  image: "https://www.uudoon.in/about/images/about-image-1.jpg",
  logo: "https://doonmanagementschool.in/wp-content/uploads/2023/04/University-logo-new-oct-scaled-1.jpg",
  year: 2024,
  naac: "A+",
  rank: "200th",
  founded: 2013,
  creditPoints: "80+",
  semesters: 4,
  duration: "2 Years",
  course: "Online MBA",
  semesterFees: "₹20,500",
  applicationFees: "₹0",
  totalFees: "₹92,000",
  emiPlan: true
},
6:{
  id: 6,
  name: "GLA University",
  location: "Mathura, India",
  description: "GLA University is a private university in Mathura, Uttar Pradesh. It is recognized by University Grants Commission, NCTE and Pharmacy Council of India. It has been accredited by the National Assessment and Accreditation Council with ‘A+’ Grade.",
  image: "https://www.gla.ac.in/images/institute-overview.jpg",
  logo: "https://upload.wikimedia.org/wikipedia/en/4/42/GLA_University_logo.png",
  year: 2025,
  naac: "A+",
  rank: "101st",
  founded: 2010,
  creditPoints: "110",
  semesters: 4,
  duration: "2 Years",
  course: "Online MBA",
  semesterFees: "₹24,000",
  applicationFees: "₹1,000",
  totalFees: "₹90,000",
  emiPlan: true
},
7:{
  id: 7,
  name: "Chandigarh University",
  location: "Mohali, India",
  description: "Chandigarh University (CU) is a private university located in Mohali, India. The university was established on 10 July 2012 by an act of Punjab State Legislature. It is recognized by University Grants Commission under Section 2(f) with the right to confer degrees as per Section 22(1) of the UGC Act, 1956.",
  image: "https://blogger.googleusercontent.com/img/a/AVvXsEhhTgvVUO5-bFLFJXtTovOE_f4gMjD1ACVzTfZNKtZonYTe77nV8dSeymhqePAkIFqdKMMvTcAfyFyE2KHVdn5E2wlmQM2y_4ukcw-1Op7EE60jOXY-2qwAqSXvThKC8ldt6LLcdOUYLMNyQvQyXeNT5YEq590_0Nq_frXh9WzPEmUx55T1Ufyj-SLkfw=s16000",
  logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-Mx5Ca8jO1s4RjWBQKke3YPNGUsLU2KCrMA&s",
  year: 2024,
  naac: "A+",
  rank: "20th",
  founded: "N/A",
  creditPoints: "80",
  semesters: 4,
  duration: "2 Years",
  course: "Online MBA",
  semesterFees: "₹37,500",
  applicationFees: "₹0",
  totalFees: "₹200,000",
  emiPlan: true
},
8:{
  id: 8,
  name: "Narsee Monjee Institute of Management Studies",
  location: "Mumbai, Maharashtra",
  description:
    "Shri Vile Parle Kelavani Mandal's Narsee Monjee Institute of Management Studies (abbreviated as SVKM's NMIMS) is a private deemed university located in Mumbai. It has 17 constituent schools that offer both undergraduate and postgraduate courses in management, engineering, commerce, pharmacy, architecture, economics, mathematical sciences, hospitality, science, law, aviation, liberal arts, performing arts, architecture & design.",
  image: "https://upload.wikimedia.org/wikipedia/commons/2/2a/NMIMS_Campus.jpg",
  logo: "https://upload.wikimedia.org/wikipedia/en/1/1e/NMIMS_Logo.png",
  year: 2024,
  naac: "A+",
  rank: "84th",
  founded: 1981,
  creditPoints: 58,
  semesters: 4,
  duration: "2 Years",
  course: "Executive MBA",
  semesterFees: "₹100,000",
  applicationFees: "₹1,500",
  totalFees: "₹400,000",
  emiPlan: true
}








  
  }