export const universitiesCoursesData = [
  {
    id: 1,
    name: "Amity University",
    course: "Master's of Business Administration",
    degree: "Master Degree",
    fee: "₹199,000",
    duration: "2 Years",
    emiPlan: true,
    logo: "https://upload.wikimedia.org/wikipedia/en/f/ff/Amity_University_logo.png",
  },
  {
    id: 2,
    name: "Kurukshetra University",
    course: "Master of Business Administration",
    degree: "Master Degree",
    fee: "₹90,000",
    duration: "2 Years",
    emiPlan: true,
    logo: "https://upload.wikimedia.org/wikipedia/en/1/1d/Kurukshetra_University_logo.png",
  },
  {
    id: 3,
    name: "Lovely Professional University",
    course: "Master's of Business Administration",
    degree: "Master Degree",
    fee: "₹145,600",
    duration: "2 Years",
    emiPlan: true,
    logo: "https://i.pinimg.com/736x/c9/12/d4/c912d49f5f63e3c25aae2465f7577e7a.jpg",
  },

  {
    id: 4,
    name: "Jain University",
    course: "Master's of Business Administration",
    degree: "Master Degree",
    fee: "₹200,000",
    duration: "2 Years",
    emiPlan: true,
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5kW1QiwZI1mxMzldLk3AV3fhz6-Wmivebmw&s",
  },
  {
    id: 5,
    name: "Uttaranchal University",
    course: "Master's of Business Administration",
    degree: "Master Degree",
    fee: "₹92,000",
    duration: "2 Years",
    emiPlan: true,
    logo: "https://doonmanagementschool.in/wp-content/uploads/2023/04/University-logo-new-oct-scaled-1.jpg",
  },
  {
    id: 6,
    name: "GLA University",
    course: "Master's of Business Administration",
    degree: "Master Degree",
    fee: "₹90,000",
    duration: "2 Years",
    emiPlan: true,
    logo: "https://upload.wikimedia.org/wikipedia/en/4/42/GLA_University_logo.png",
  },
  {
    id: 7,
    name: "Chandigarh University",
    course: "Master's of Business Administration",
    degree: "Master Degree",
    fee: "₹200,000",
    duration: "2 Years",
    emiPlan: true,
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-Mx5Ca8jO1s4RjWBQKke3YPNGUsLU2KCrMA&s",
  },
  {
    id: 8,
    name: "Narsee Monjee Institute of Management Studies",
    course: "Master's of Business Administration",
    degree: "Master Degree",
    fee: "₹220,000",
    duration: "2 Years",
    emiPlan: true,
    logo: "https://pbs.twimg.com/profile_images/887620877138907136/Zau4_WSX_400x400.jpg",
  },
  {
    id: 9,
    name: "Amrita Vishwa Vidyapeetham",
    course: "Master's of Business Administration",
    degree: "Master Degree",
    fee: "₹1,75,000",
    duration: "2 Years",
    emiPlan: true,
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Amrita-vishwa-vidyapeetham-logo.svg/2560px-Amrita-vishwa-vidyapeetham-logo.svg.png"
  },
  {
    id: 10,
    name: "Parul University",
    course: "Master's of Business Administration",
    degree: "Master Degree",
    fee: "₹90,000",
    duration: "2 Years",
    emiPlan: true,
    logo: "https://i.pinimg.com/736x/35/4e/41/354e41b970004cac05cbe77bbc681ad8.jpg"
  },
  {
    id: 11,
    name: "Shoolini University",
    course: "Master's of Business Administration",
    degree: "Master Degree",
    fee: "₹1,20,000",
    duration: "2 Years",
    emiPlan: true,
    logo: "https://online.shooliniuniversity.com/distance/assets/img/logo.png"
  },
  {
    id: 12,
    name: "Sharda University",
    course: "Master's of Business Administration",
    degree: "Master Degree",
    fee: "₹1,50,000",
    duration: "2 Years",
    emiPlan: true,
    logo: " https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTK4Pd52Bzy8GLLUsBcY91yPN0VFzkERuN7-g&s"
  },
  {
    id: 13,
    name: "Sikkim Manipal University",
    course: "Master's of Business Administration",
    degree: "Master Degree",
    fee: "₹1,30,000",
    duration: "2 Years",
    emiPlan: true,
    logo: "https://content.jdmagicbox.com/comp/dehradun/w1/9999pd135.d135.110721154744.r1w1/catalogue/sikkim-manipal-university-toll-free-no-dehradun-gpo-dehradun-institutes-for-disaster-management-klht5.jpg"
  },
  {
    id: 14,
    name: "UPES (University of Petroleum and Energy Studies)",
    course: "Master's of Business Administration",
    degree: "Master Degree",
    fee: "₹1,80,000",
    duration: "2 Years",
    emiPlan: true,
    logo: " https://indiaeducationdiary.in/wp-content/uploads/2022/01/UPES-LOGO-01.jpg?w=640"
  },
  {
    id: 15,
    name: "Vignan's University",
    course: "Master's of Business Administration",
    degree: "Master Degree",
    fee: "₹70,000",
    duration: "2 Years",
    emiPlan: true,
    logo: "https://content.jdmagicbox.com/v2/comp/hyderabad/64/040p7005064/catalogue/vignan-institute-of-technology-and-science-kukatpally-hyderabad-engineering-colleges-pe113r.jpg"
  },
  {
    id: 16,
    name: "Vivekananda Global University",
    course: "Master's of Business Administration",
    degree: "Master Degree",
    fee: "₹85,000",
    duration: "2 Years",
    emiPlan: true,
    logo: "https://upload.wikimedia.org/wikipedia/commons/8/8f/Vivekananda-global-university-jaipur.jpg"
  },
  {
    id: 17,
    name: "Aligarh Muslim University",
    course: "Master's of Business Administration",
    degree: "Master Degree",
    fee: "₹1,00,000",
    duration: "2 Years",
    emiPlan: false,
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQskJ0c3dzaabVW_PWcxTUViMR2PQmpHOKfJg&s"
  },
  {
    id: 18,
    name: "Andhra University, Visakhapatnam, Andhra Pradesh",
    course: "Master's of Business Administration",
    degree: "Master Degree",
    fee: "₹70,000",
    duration: "2 Years",
    emiPlan: false,
    logo: " https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAMJ1BwQisVClB5CvBgI40-5Y0ZJkgyYqT3g&s"
  },
  {
    id: 19,
    name: "D.Y. Patil University",
    course: "Master's of Business Administration",
    degree: "Master Degree",
    fee: "₹1,25,000",
    duration: "2 Years",
    emiPlan: true,
    logo: "https://static.wixstatic.com/media/bff831_b2037f9baf424ffeb229a275ab3da890~mv2.png/v1/fill/w_518,h_222,al_c,lg_1,q_85,enc_avif,quality_auto/dyp-online-logo.png"
  },
  {
    id: 20,
    name: "Manipal University",
    course: "Master's of Business Administration",
    degree: "Master Degree",
    fee: "₹2,00,000",
    duration: "2 Years",
    emiPlan: true,
    logo: " https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFphxje5ISCTbvjGYFf7rCUIElnSbP9ovxpg&s"
  },
  {
    id: 21,
    name: "Dr. D. Y. Patil Vidyapeeth University (DPU)",
    course: "Master's of Business Administration",
    degree: "Master Degree",
    fee: "₹1,40,000",
    duration: "2 Years",
    emiPlan: true,
    logo: "https://upload.wikimedia.org/wikipedia/commons/8/87/Dr._D._Y._Patil_Medical_College%2C_Hospital_%26_Research_Centre_logo.jpg"
  },
  {
    id: 22,
    name: "Jamia Hamdard University",
    course: "Master's of Business Administration",
    degree: "Master Degree",
    fee: "₹1,10,000",
    duration: "2 Years",
    emiPlan: true,
    logo: "https://jamiahamdard.edu/images/top-logo.png"
  },
  {
    id: 23,
    name: "Mizoram University",
    course: "Master's of Business Administration",
    degree: "Master Degree",
    fee: "₹60,000",
    duration: "2 Years",
    emiPlan: false,
    logo: " https://www.yugedu.com/media/654/mizoram-university-online-logo.png"
  }
];

      
      
  
